/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeu_isotopic_256;

/**
 *
 * @author Lubos
 */
public class FAccueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil_Jeu_Isotopic_256
     */
    
    private FChoixJeu fichChoix;
    private FJouer fichJouer;
    
    
    
    public FAccueil() {
        this.setLocation(550,300);
        this.setTitle(" Accueil du jeu");
        initComponents();
        fichChoix = new FChoixJeu(this,false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PA_Image = new javax.swing.JPanel();
        bJouer = new javax.swing.JButton();
        bCharger = new javax.swing.JButton();
        JImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jeu_isotopic_256/Jeu Isotopic 256.png"))); // NOI18N
        jLabel1.setLabelFor(jLabel1);

        PA_Image.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        bJouer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bJouer.setForeground(new java.awt.Color(153, 0, 0));
        bJouer.setText("Jouer");
        bJouer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bJouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJouerActionPerformed(evt);
            }
        });

        bCharger.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bCharger.setForeground(new java.awt.Color(153, 0, 0));
        bCharger.setText("Charger");
        bCharger.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChargerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PA_ImageLayout = new javax.swing.GroupLayout(PA_Image);
        PA_Image.setLayout(PA_ImageLayout);
        PA_ImageLayout.setHorizontalGroup(
            PA_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PA_ImageLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(bJouer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCharger)
                .addGap(87, 87, 87))
            .addGroup(PA_ImageLayout.createSequentialGroup()
                .addGap(499, 499, 499)
                .addComponent(JImage)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        PA_ImageLayout.setVerticalGroup(
            PA_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PA_ImageLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(JImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addGroup(PA_ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCharger)
                    .addComponent(bJouer))
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PA_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PA_Image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChargerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bChargerActionPerformed

    private void bJouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJouerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichChoix.setVisible(true);
    }//GEN-LAST:event_bJouerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JImage;
    private javax.swing.JPanel PA_Image;
    private javax.swing.JButton bCharger;
    private javax.swing.JButton bJouer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
